config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'likes/create'
  get 'likes/destroy'
  get 'responses/create'
  get 'responses/destroy'
  get 'users/show'
  devise_for :users, module: :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static_pages#home'
  resources :users, only: [:show] do
    member do
      get :likes
    end
  end
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :responses, only: [:create, :destroy]
  # patch 'resolutions', to: 'resolutions#close'
  match '/close', to: 'resolutions#close', via: 'patch'
  resources :likes, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :best_answers, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :favorites, dependent: :destroy
  default_scope -> { order(created_at: :desc) }

  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 10000 }
  validates :user_id, presence: true
  # 質問の解決or未解決判定用。デフォルトは0、解決後1
  validates :resolution, presence: true

  # like数の上位10を抽出
  def self.ranking
    self.reorder('liker DESC').limit(10)
  end

  # 検索機能
  def self.search(search)
    search ? self.where(['title LIKE ?', "%#{search}%"]) : self.all
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  PER = 20

  def index
    @questions = Question.page(params[:page]).search(params[:search]).per(PER)
    @user_rankings = User.ranking
    @question_rankings = Question.ranking
  end

  def new
    @question = current_user.questions.build
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      flash[:notice] = "投稿しました。"
      redirect_to root_url
    else
      flash[:alert] = "失敗しました。"
      redirect_to new_question_path
    end
  end

  def show
    @question = Question.find_by(id: params[:id])
    @user     = User.find_by(id: @question.user_id)
    @user_rankings = User.ranking
    @question_rankings = Question.ranking
    if user_signed_in?
      @answer = current_user.answers.build
      @response = current_user.responses.build
    end
  end

  def edit
    @question = Question.find_by(id: params[:id])
  end

  def update
    @question = Question.find_by(id: params[:id])
    @question.update_attributes(question_params) ? flash[:notice] = "編集しました。"
                                                 : flash[:alert] = "失敗しました。タイトルもしくは本文が空欄のようです。"
    redirect_to @question
  end

  def destroy
    @question = Question.find_by(id: params[:id])
    @question.destroy
    flash[:notice] = "削除しました。"
    redirect_to root_url
  end

  private

    def question_params
      params.require(:question).permit(:title, :tag, :content)
    end

    def correct_user
      @question = current_user.questions.find_by(id: params[:id])
      redirect_to root_url if @question.nil?
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<% provide :title, "質問の変更" %>
<div class="main">
  <div class="question-form">
    <%= form_for @question do |f| %>

      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: "title-form", autocomplete: "off", placeholder: "タイトル" %>

      <%= f.label :content, "本文" %>
      <%= f.text_area :content, class: "content-form", autocomplete: "off", placeholder: "本文" %>

      <%= f.submit "更新する", class: "question-submit-btn" %>

    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<% provide :title, "質問一覧" %>
<div class="main">
  <div class="row">
    <div class="col-md-8">
      <div class="questions">
        <div class="questions-title">
          <% if params[:search] %>
            <h4>
              　<span class="glyphicon glyphicon-align-left">　「<%= params[:search] %>」の検索結果
              <% if @questions.count == 0 %>
                見つかりませんでした。（<%= link_to "質問を投稿する", new_question_path %>）
              <% end %>
            </h4>
          <% else %>
            <h4>　<span class="glyphicon glyphicon-align-left">　新着の質問一覧</h4>
          <% end %>
        </div>
        <% @questions.each do |question| %>
        <div class="question">
          <% unless question.user.avatar.nil? %>
            <%= link_to "users/#{question.user.id}" do %>
              <%= image_tag question.user.avatar.url, size: 50, class: "avatar-in-question-info question-left" %>
            <% end %>
          <% else %>
            <%= link_to "users/#{question.user.id}" do %>
              <%= image_tag "default.jpg", size: 50, class: "avatar-in-question-info question-left" %>
            <% end %>
          <% end %>

          <% if question.title.size >= 33 %>
            <%= link_to "#{question.title[0,31]}...", question, class: "question-link" %><br>
          <% else %>
            <%= link_to question.title, question, class: "question-link" %><br>
          <% end %>
          <p>by_
            <%= link_to "users/#{question.user.id}" do %>
              <%= question.user.name %>
            <% end %>
          </p>
          <%= time_ago_in_words(question.created_at) %>前
        </div>
        <% end %>
        <%= paginate @questions, :window => 2 %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="ranking">
        <%= render 'shared/question_search' %>
        <%= render 'shared/user_ranking' %>
        <%= render 'shared/question_ranking' %>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<% provide :title, "質問する" %>
<div class="main">
  <div class="question-form">
    <%= form_for @question do |f| %>

      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: "title-form", autocomplete: "off", placeholder: "タイトル" %>

      <%= f.label :content, "本文" %>
      <%= f.text_area :content, class: "content-form", autocomplete: "off", placeholder: "本文" %>

      <%= f.submit "投稿する", class: "question-submit-btn" %>

    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<% provide :title, "#{@question.title}" %>
<div class="main">
  <div class="row">
    <div class="col-md-8 col-sm-12">
      <!-- 質問内容 -->
      <div class="question-info">
        <h1>
          <% unless @user.avatar.nil? %>
            <%= image_tag @user.avatar.url, size: 40, class: "avatar-in-question-info" %>
          <% else %>
            <%= image_tag "default.jpg", size: 40, class: "avatar-in-question-info" %>
          <% end %>
          <p class="user-name-in-questions-show"><%= link_to @user.name, @user %></p>
          <p class="posted-time-in-questions-show"><%= time_ago_in_words(@question.created_at) %>前</p><br>
          <p class="question-title-in-questions-show"><%= @question.title %></p>
        </h1>
        <% if @question.resolution == 0 %>
          <p class="question-acceptance-state">（この質問は回答を受付中です。）</p>
        <% else %>
          <p class="question-acceptance-state">（この質問は回答を締め切りました。）</p>
        <% end %>
        <!-- 質問へのいいね -->
        <% if user_signed_in? %>
          <% if current_user.favorite?(@question) %>
            <%= form_for current_user.favorites.find_by(question_id: @question.id), method: "delete" do |f| %>
              <%= hidden_field_tag :question_id, @question.id %>
              <%= button_tag type: "submit", class: "unfavorite-btn" do %>
                <span class="glyphicon glyphicon-ok"><span class="liker-number"><%= @question.liker %></span>
              <% end %>
            <% end %>
          <% else %>
            <%= form_for current_user.favorites.build, method: "post" do |f| %>
              <%= hidden_field_tag :question_id, @question.id %>
              <%= button_tag type: "submit", class: "favorite-btn" do %>
                <span class="glyphicon glyphicon-heart-empty"><span class="liker-number"><%= @question.liker %></span>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
        <p class="question-content-in-questions-show"><%= @question.content %></p>
        <% if user_signed_in? && @question.user_id == current_user.id %>
          <% if @question.resolution == 0 %>
            <p class="question-close-link"><%= link_to "締め切る", close_path(@question, question_id: @question.id), method: :patch, data: { confirm: "質問を締め切りますか？" } %></p>
            <p class="question-edit-link"><%= link_to "編集", edit_question_path(@question) %></p>
          <% end %>
          <p class="question-delete-link"><%= link_to "削除", question_path, method: :delete, data: { confirm: "削除しますか？" } %></p>
        <% end %>
        <!-- 回答一覧 -->
        <div class="answers">
          <p class="answers-title">回答一覧</p>
          <div class="answer">
            <% @question.answers.each_with_index do |answer, index| %>
              <!-- 回答内容 -->
              <div class="answer-info-wrapper clearfix">
                <div class="answer-info-left">
                  <% unless @user.avatar.nil? %>
                    <%= image_tag answer.user.avatar.url, size: 40, class: "avatar-in-answer-info answer-left" %>
                  <% else %>
                    <%= image_tag "default.jpg", size: 40, class: "avatar-in-answer-info answer-left" %>
                  <% end %>
                  <p>NO.<%= index + 1 %>：<%= link_to answer.user.name, answer.user %>　<%= time_ago_in_words(answer.created_at) %>前</p>
                </div>
                <div class="answer-info-right">
                  <% if answer.id == @question.best_answer_id %>
                    <%= image_tag "best_answer.png", size: 50 %>
                  <% end %>
                </div>
              </div>
              <div class="answer-content">
                <p><%= answer.content %></p>
                <% if user_signed_in? %>
                  <% if answer.user_id == current_user.id %>
                    <%= link_to "回答を削除する", answer_path(answer), method: :delete, data: { confirm: "削除しますか？" }, class: "btn" %>
                  <% elsif current_user.like?(answer) %>
                    <%= form_for(current_user.likes.find_by(answer_id: answer.id), method: :delete, html: { class: "unlike-form" }) do |f| %>
                      <%= hidden_field_tag :answer_id, answer.id %>
                      <%= f.submit 'いいね済み', class: "unlike-btn" %>
                    <% end %>
                  <% else %>
                    <%= form_for(current_user.likes.build, html: { class: "like-form" }) do |f| %>
                      <%= hidden_field_tag :answer_id, answer.id %>
                      <%= f.submit 'いいね', class: "like-btn" %>
                    <% end %>
                  <% end %>
                  <% if current_user.id == @question.user_id && @question.resolution == 0 %>
                    <% if @question.best_answer_id == answer.id %>
                      <%= form_for @question, url: "/best_answers/:id", method: "delete", data: { confirm: "ベストアンサーを取り消しますか？" }, html: { class: "destroy-best-answer-form" } do |f| %>
                        <%= hidden_field_tag :question_id, @question.id %>
                        <%= hidden_field_tag :answer_id, answer.id %>
                        <%= f.submit 'ベストアンサーを取り消す', class: "destroy-best-answer-btn" %>
                      <% end %>
                    <% elsif @question.best_answer_id.nil? %>
                      <%= form_for @question, url: "/best_answers", method: "post", html: { class: "create-best-answer-form" } do |f| %>
                        <%= hidden_field_tag :question_id, @question.id %>
                        <%= hidden_field_tag :answer_id, answer.id %>
                        <%= f.submit 'ベストアンサーに決定する！', class: "create-best-answer-btn" %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
              <!-- 返信内容 -->
              <div class="responses">
                <% answer.responses.each do |response| %>
                  <div class="response-info">
                    <% unless @user.avatar.nil? %>
                      <%= image_tag response.user.avatar.url, size: 40, class: "avatar-in-response-info response-left" %>
                    <% else %>
                      <%= image_tag "default.jpg", size: 40, class: "avatar-in-response-info response-left" %>
                    <% end %>
                    <p><%= response.user.name %>　<%= time_ago_in_words(response.created_at) %>前</p>
                  </div>
                  <div class="response-content">
                    <p><%= response.content %></p>
                    <% if user_signed_in? && response.user_id == current_user.id %>
                      <%= link_to "返信を削除する", response_path(response), method: :delete, data: { confirm: "削除しますか？" }, class: "btn" %>
                    <% end %>
                  </div>
                <% end %>
                <!-- 返信フォーム -->
                <% if current_user == @question.user || current_user == answer.user %>
                  <div class="response-form">
                    <% if user_signed_in? && @question.resolution == 0 %>
                      <%= form_for @response do |f| %>
                        <%= f.hidden_field :user_id, value: current_user.id %>
                        <%= f.hidden_field :question_id, value: @question.id %>
                        <%= f.hidden_field :answer_id, value: answer.id %>
                        <%= f.text_area :content, class: "response-form response-content-form", autocomplete: "off", placeholder: "返信" %><br>
                        <%= f.submit "返信する", class: "response-submit-btn" %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <!-- 回答フォーム -->
        <% unless @user == current_user %>
          <div class="answer-form">
            <h4 class="answer-form-title"><%= @question.user.name %>さんの質問に回答しよう！</h4>
            <% if user_signed_in? && @question.resolution == 0 %>
              <%= form_for @answer do |f| %>
                <%= f.hidden_field :question_id, value: @question.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.text_area :content, class: "answer-form answer-content-form", autocomplete: "off", placeholder: "回答" %>
                <%= f.submit "回答する", class: "answer-submit-btn" %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <!-- ランキング -->
    <div class="col-md-4 col-sm-12">
      <%= render 'shared/question_search' %>
      <%= render 'shared/user_ranking' %>
      <%= render 'shared/question_ranking' %>
    </div>
  </div>
</div>