config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'likes/create'
  get 'likes/destroy'
  get 'responses/create'
  get 'responses/destroy'
  get 'users/show'
  devise_for :users, module: :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static_pages#home'
  resources :users, only: [:show] do
    member do
      get :likes
    end
  end
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :responses, only: [:create, :destroy]
  # patch 'resolutions', to: 'resolutions#close'
  match '/close', to: 'resolutions#close', via: 'patch'
  resources :likes, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :best_answers, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likings, through: :likes, source: :answer
  has_many :favorites, dependent: :destroy
  has_many :favoritings, through: :favorites, source: :question
  validates :name, presence: true
  attr_accessor :confirmed_at
  mount_uploader :avatar, AvatarUploader

  # 開発環境でメール認証を避ける（本番環境ではコメントアウトする）
  def active_for_authentication?
    true
  end

  # 回答へのいいね
  def like(answer)
    self.likes.find_or_create_by(answer_id: answer.id)
    answer.user.liker += 1
    answer.user.save
  end

  def unlike(answer)
    like = self.likes.find_by(answer_id: answer.id)
    like.destroy if like
    answer.user.liker -= 1
    answer.user.save
  end

  def like?(answer)
    self.likings.include?(answer)
  end

  # 質問へのいいね
  def favorite(question)
    self.favorites.find_or_create_by(question_id: question.id)
    question.liker += 1
    question.save
    question.user.liker += 1
    question.user.save
  end

  def unfavorite(question)
    favorite = self.favorites.find_by(question_id: question.id)
    favorite.destroy if favorite
    question.liker -= 1
    question.save
    question.user.liker -= 1
    question.user.save
  end

  def favorite?(question)
    self.favoritings.include?(question)
  end

  # like数の上位10人を抽出
  def self.ranking
    self.order('liker DESC').limit(10)
  end

  # ツイッターログイン用の設定
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        image: auth.info.image,
        name: auth.info.name,
        nickname: auth.info.nickname,
        location: auth.info.location
      )
    end

    user
  end

  private

    # ツイッターログイン用の設定
    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def twitter
    callback_from :twitter
  end

  private

    def callback_from(provider)
      provider = provider.to_s

      @user = User.find_for_oauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.#{provider}_data"] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  PER = 10

  def show
    @user = User.find_by(id: params[:id])
    @questions = Question.where(user_id: @user.id).page(params[:page]).per(PER)
  end

  def likes
    @user = User.find_by(id: params[:id])
    @questions = @user.favoritings.page(params[:page]).per(PER)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/likes.html.erb
<% provide :title, "マイページ" %>
<div class="my-page clearfix">
  <div class="col-md-3 col-sm-12 my-page-left">
    <% unless @user.avatar.nil?%>
      <%= image_tag @user.avatar.url, size: 250, class: "avatar-in-my-page" %>
    <% else %>
      <%= image_tag "default.jpg", size: 250, class: "avatar-in-my-page" %>
    <% end %>
    <h2><%= @user.name %></h2>
    <% if @user == current_user %>
      <span class="glyphicon glyphicon-asterisk color-999"></span><%= link_to "プロフィールを編集する", "/users/edit", class: "color-999" %>
    <% end %>
    <br>獲得いいね数：<%= @user.liker %>
  </div>
  <div class="col-md-9 col-sm-12 my-page-right">
    <div class="my-questions">
      <div class="my-questions-title">
        <h4 class="my-questions1">　　　<%= link_to "投稿した質問一覧", "/users/#{@user.id}" %></h4>
        <h4 class="my-questions2 my-questions-active">　<span class="glyphicon glyphicon-align-left">　いいねした質問</h4>
      </div>
      <% @questions.each do |question| %>
        <div class="my-question">
          <% unless question.user.avatar.nil? %>
            <%= image_tag question.user.avatar.url, size: 50, class: "avatar-in-question-info question-left" %>
          <% else %>
            <%= image_tag "default.jpg", size: 50, class: "avatar-in-question-info question-left" %>
          <% end %>
          <% if question.title.size >= 33 %>
            <%= link_to "#{question.title[0,31]}...", question, class: "question-link" %><br>
          <% else %>
            <%= link_to question.title, question, class: "question-link" %><br>
          <% end %>
          <p>by_<%= question.user.name %></p>
          <%= time_ago_in_words(question.created_at) %>前
        </div>
      <% end %>
      <%= paginate @questions, :window => 2 %>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/users/show.html.erb
<% provide :title, "マイページ-いいね一覧-" %>
<div class="my-page clearfix">
  <div class="col-md-3 col-sm-12 my-page-left">
    <% unless @user.avatar.nil?%>
      <%= image_tag @user.avatar.url, size: 250, class: "avatar-in-my-page" %>
    <% else %>
      <%= image_tag "default.jpg", size: 250, class: "avatar-in-my-page" %>
    <% end %>
    <h2><%= @user.name %></h2>
    <% if @user == current_user %>
      <span class="glyphicon glyphicon-asterisk color-999"></span><%= link_to "プロフィールを編集する", "/users/edit", class: "color-999" %>
    <% end %>
    <br>獲得いいね数：<%= @user.liker %>
  </div>
  <div class="col-md-9 col-sm-12 my-page-right">
    <div class="my-questions">
      <div class="my-questions-title">
        <h4 class="my-questions1 my-questions-active">　<span class="glyphicon glyphicon-align-left">　投稿した質問一覧</h4>
        <h4 class="my-questions2">　　　<%= link_to "いいねした質問", likes_user_path %></h4>
      </div>
      <% @questions.each do |question| %>
        <div class="my-question">
          <% unless question.user.avatar.nil? %>
            <%= image_tag question.user.avatar.url, size: 50, class: "avatar-in-question-info question-left" %>
          <% else %>
            <%= image_tag "default.jpg", size: 50, class: "avatar-in-question-info question-left" %>
          <% end %>
          <% if question.title.size >= 33 %>
            <%= link_to "#{question.title[0,31]}...", question, class: "question-link" %><br>
          <% else %>
            <%= link_to question.title, question, class: "question-link" %><br>
          <% end %>
          <p>by_<%= question.user.name %></p>
          <%= time_ago_in_words(question.created_at) %>前
        </div>
      <% end %>
      <%= paginate @questions, :window => 2 %>
    </div>
  </div>
  <div class="clear"></div>
</div>