config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'likes/create'
  get 'likes/destroy'
  get 'responses/create'
  get 'responses/destroy'
  get 'users/show'
  devise_for :users, module: :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static_pages#home'
  resources :users, only: [:show] do
    member do
      get :likes
    end
  end
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :responses, only: [:create, :destroy]
  # patch 'resolutions', to: 'resolutions#close'
  match '/close', to: 'resolutions#close', via: 'patch'
  resources :likes, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :best_answers, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :responses, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes, source: :user

  validates :content, presence: true, length: { maximum: 10000 }
  validates :user_id, presence: true
  validates :question_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :user_id, presence: true
  validates :question_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :answer

  validates :user_id, presence: true
  validates :answer_id, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :favorites, dependent: :destroy
  default_scope -> { order(created_at: :desc) }

  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 10000 }
  validates :user_id, presence: true
  # 質問の解決or未解決判定用。デフォルトは0、解決後1
  validates :resolution, presence: true

  # like数の上位10を抽出
  def self.ranking
    self.reorder('liker DESC').limit(10)
  end

  # 検索機能
  def self.search(search)
    search ? self.where(['title LIKE ?', "%#{search}%"]) : self.all
  end

end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :answer

  validates :content, presence: true, length: { maximum: 10000 }
  validates :user_id, presence: true
  validates :question_id, presence: true
  validates :answer_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likings, through: :likes, source: :answer
  has_many :favorites, dependent: :destroy
  has_many :favoritings, through: :favorites, source: :question
  validates :name, presence: true
  attr_accessor :confirmed_at
  mount_uploader :avatar, AvatarUploader

  # 開発環境でメール認証を避ける（本番環境ではコメントアウトする）
  def active_for_authentication?
    true
  end

  # 回答へのいいね
  def like(answer)
    self.likes.find_or_create_by(answer_id: answer.id)
    answer.user.liker += 1
    answer.user.save
  end

  def unlike(answer)
    like = self.likes.find_by(answer_id: answer.id)
    like.destroy if like
    answer.user.liker -= 1
    answer.user.save
  end

  def like?(answer)
    self.likings.include?(answer)
  end

  # 質問へのいいね
  def favorite(question)
    self.favorites.find_or_create_by(question_id: question.id)
    question.liker += 1
    question.save
    question.user.liker += 1
    question.user.save
  end

  def unfavorite(question)
    favorite = self.favorites.find_by(question_id: question.id)
    favorite.destroy if favorite
    question.liker -= 1
    question.save
    question.user.liker -= 1
    question.user.save
  end

  def favorite?(question)
    self.favoritings.include?(question)
  end

  # like数の上位10人を抽出
  def self.ranking
    self.order('liker DESC').limit(10)
  end

  # ツイッターログイン用の設定
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        image: auth.info.image,
        name: auth.info.name,
        nickname: auth.info.nickname,
        location: auth.info.location
      )
    end

    user
  end

  private

    # ツイッターログイン用の設定
    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!


  def create
    @question = Question.find_by(id: params[:answer][:question_id])
    @answer = @question.answers.build(answer_params)
    @answer.save ? flash[:notice] = "回答しました。" : flash[:alert] = "失敗しました。"
    redirect_to @question
  end

  def destroy
    @answer = Answer.find_by(id: params[:id])
    @question = Question.find_by(id: @answer.question_id)
    @answer.destroy
    flash[:notice] = "削除しました。"
    redirect_to @question
  end

  private

    def answer_params
      params.require(:answer).permit(:content, :question_id, :user_id)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    answer = Answer.find_by(id: params[:answer_id])
    current_user.like(answer)
    flash[:notice] = "いいねしました。"
    redirect_to answer.question
  end

  def destroy
    answer = Answer.find_by(id: params[:answer_id])
    current_user.unlike(answer)
    flash[:notice] = "いいねを取り消しました。"
    redirect_to answer.question
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  PER = 10

  def show
    @user = User.find_by(id: params[:id])
    @questions = Question.where(user_id: @user.id).page(params[:page]).per(PER)
  end

  def likes
    @user = User.find_by(id: params[:id])
    @questions = @user.favoritings.page(params[:page]).per(PER)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/best_answers_helper.rb
module BestAnswersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/resolutions_helper.rb
module ResolutionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  Copyright © 2018 Fiita All Rights Reserved.
</footer>

app/views/layouts/_head_setting.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://fonts.googleapis.com/css?family=Kreon:400,700" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

<%= favicon_link_tag() %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to image_tag("Fiita_logo.png", height: 60,id: "logo"), root_path, id: "logo" %>
    <% if user_signed_in? %>
      <span class="user-name"><%= current_user.name %>様</span>
    <% end %>
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navber-right navbar-logged-in">
        <li><%= link_to "質問する", "/questions/new", class: "new-link-for-rspec" %></li>
        <li><%= link_to "回答する", "/questions" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            アカウント <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li class="dropdown-menu-list"><%= link_to "マイページ", current_user, class: "dropdown-link" %></li>
            <li class="dropdown-menu-list"><%= link_to "登録情報変更", "/users/edit", class: "dropdown-link" %></li>
            <li class="divider"></li>
            <li class="dropdown-menu-list"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-link" %></li>
          </ul>
        </li>
        <span class="user-name-in-device show-in-device"><%= current_user.name %>様</span>
      </div>
    <% else %>
      <ul class="nav navbar-nav navber-right navbar-guest">
        <li><%= link_to "新規登録", "/users/sign_up", class: "users-signup-btn" %></li>
        <li><%= link_to "ログイン", "/users/sign_in" %></li>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class="account-menu">
      <%= link_to "質問する", "/questions/new", class: "account-link account-link1" %>
      <%= link_to "回答する", "/questions", class: "account-link account-link2" %>
      <%= link_to "マイページ", current_user, class: "account-link account-link3" %>
      <%= link_to "登録情報変更", "/users/edit", class: "account-link account-link4" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "account-link account-link5" %>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= render 'layouts/head_setting' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_question_new.html.erb
<div class="question-form">
  <%= form_for @question do |f| %>

    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: "title-form", autocomplete: "off", placeholder: "タイトル" %>

    <%= f.label :content, "本文" %>
    <%= f.text_area :content, class: "content-form", autocomplete: "off", placeholder: "本文" %>

    <%= f.submit "投稿する", class: "question-submit-btn" %>

  <% end %>
</div>

app/views/shared/_question_ranking.html.erb
<div class="question_ranking">
  <h2><span class="glyphicon glyphicon-user"></span>　質問ランキング</h2>
  <% @question_rankings.each_with_index do |question, index| %>
  <div class="rank_in_user">
      <div class="rank_number">
        <% case index %>
        <% when 0 %>
          <%= image_tag "q&a_app_gold_user.jpg", size:26, class: "trophy" %>
        <% when 1 %>
          <%= image_tag "q&a_app_silver_user.jpg", size:26, class: "trophy" %>
        <% when 2 %>
          <%= image_tag "q&a_app_bronze_user.jpg", size:26, class: "trophy" %>
        <% else %>
          <%= index + 1 %>
        <% end %>
      </div>
      <% if question.user.avatar? %>
        <%= link_to "users/#{question.user.id}" do %>
          <%= image_tag question.user.avatar.url, size: 30 %>
        <% end %>
      <% else %>
        <%= link_to "users/#{question.user.id}" do %>
          <%= image_tag "default.jpg", size: 30 %>
        <% end %>
      <% end %>
      <div class="rank_in_user_name">
        <% if question.title.size >= 15 %>
          <%= link_to "#{question.title[0,13]}...", question, class: "question-link-in-ranking" %><br>
        <% else %>
          <%= link_to question.title, question, class: "question-link-in-ranking" %><br>
        <% end %>
      </div>
      <div class="rank_in_user_liker"><%= question.liker %>いいね</div>
  </div>
  <% end %>
</div>

app/views/shared/_question_search.html.erb
<div class="question-search">
  <h2><span class="glyphicon glyphicon-search"></span>質問を検索</h2>
  <%= form_tag questions_path, method: "get" do |f| %>
    <%= text_field_tag :search, params[:search], class: "question-search-form" %>
    <%= submit_tag "検索", :name => nil, class: "question-search-btn" %>
  <% end %>
</div>

app/views/shared/_ranking.html.erb
<div class="ranking">
  <h2><span class="glyphicon glyphicon-user"></span>　ユーザーランキング</h2>
  <% @rankings.each_with_index do |user, index| %>
  <div class="rank_in_user">
      <div class="rank_number">
        <% case index %>
        <% when 0 %>
          <%= image_tag "q&a_app_gold_user.jpg", size:26, class: "trophy" %>
        <% when 1 %>
          <%= image_tag "q&a_app_silver_user.jpg", size:26, class: "trophy" %>
        <% when 2 %>
          <%= image_tag "q&a_app_bronze_user.jpg", size:26, class: "trophy" %>
        <% else %>
          <%= index + 1 %>
        <% end %>
      </div>
      <% if user.avatar? %>
        <%= image_tag user.avatar.url, size: 30 %>
      <% else %>
        <%= image_tag "default.jpg", size: 30 %>
      <% end %>
      <div class="rank_in_user_name"><%= link_to user.name, user %></div>
      <div class="rank_in_user_liker"><%= user.liker %>いいね</div>
  </div>
  <% end %>
</div>

app/views/shared/_user_ranking.html.erb
<div class="user_ranking">
  <h2><span class="glyphicon glyphicon-user"></span>　ユーザーランキング</h2>
  <% @user_rankings.each_with_index do |user, index| %>
  <div class="rank_in_user">
      <div class="rank_number">
        <% case index %>
        <% when 0 %>
          <%= image_tag "q&a_app_gold_user.jpg", size:26, class: "trophy" %>
        <% when 1 %>
          <%= image_tag "q&a_app_silver_user.jpg", size:26, class: "trophy" %>
        <% when 2 %>
          <%= image_tag "q&a_app_bronze_user.jpg", size:26, class: "trophy" %>
        <% else %>
          <%= index + 1 %>
        <% end %>
      </div>
      <% if user.avatar? %>
        <%= link_to "users/#{user.id}" do %>
          <%= image_tag user.avatar.url, size: 30 %>
        <% end %>
      <% else %>
        <%= link_to "users/#{user.id}" do %>
          <%= image_tag "default.jpg", size: 30 %>
        <% end %>
      <% end %>
      <div class="rank_in_user_name"><%= link_to user.name, user %></div>
      <div class="rank_in_user_liker"><%= user.liker %>いいね</div>
  </div>
  <% end %>
</div>